#!/usr/bin/env python3
"""Offline OpenAPI -> TypeScript client codegen for Plateboard (no network)."""
import sys
import yaml

TS_TYPES = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}

def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    t = schema.get("type", "unknown")
    if t == "array":
        return ts_type(schema["items"]) + "[]"
    return TS_TYPES.get(t, "unknown")

def emit_interface(name, schema):
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, ps in schema.get("properties", {}).items():
        opt = "" if prop in required else "?"
        lines.append(f"  {prop}{opt}: {ts_type(ps)};")
    lines.append("}")
    return "\n".join(lines)

def emit_operation(path, op):
    name = op["operationId"]
    params = [p for p in op.get("parameters", []) if p.get("in") == "path"]
    args = ", ".join(f'{p["name"]}: {ts_type(p["schema"])}' for p in params)
    ret = ts_type(op["responses"]["200"]["content"]["application/json"]["schema"])
    url = "baseUrl + `" + path.replace("{", "${encodeURIComponent(").replace("}", ")}") + "`"
    arglist = ("baseUrl: string, " + args) if args else "baseUrl: string"
    return (
        f"export async function {name}({arglist}): Promise<{ret}> {{\n"
        f"  const res = await fetch({url});\n"
        f"  if (!res.ok) throw new Error(\"{name}: HTTP \" + res.status);\n"
        f"  return (await res.json()) as {ret};\n"
        f"}}"
    )

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_client.py <openapi.yaml> <out.ts>")
    with open(sys.argv[1]) as f:
        spec = yaml.safe_load(f)
    parts = ["// GENERATED by scripts/gen_client.py -- do not edit.", ""]
    for name, schema in spec.get("components", {}).get("schemas", {}).items():
        parts.append(emit_interface(name, schema))
        parts.append("")
    for path, methods in spec.get("paths", {}).items():
        for _method, op in methods.items():
            parts.append(emit_operation(path, op))
            parts.append("")
    with open(sys.argv[2], "w") as f:
        f.write("\n".join(parts))

if __name__ == "__main__":
    main()
